/*
 Navicat Premium Dump SQL

 Source Server         : root
 Source Server Type    : MySQL
 Source Server Version : 80300 (8.3.0)
 Source Host           : localhost:3306
 Source Schema         : electron_api_dev

 Target Server Type    : MySQL
 Target Server Version : 80300 (8.3.0)
 File Encoding         : 65001

 Date: 08/12/2025 00:15:04
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for categories
-- ----------------------------
DROP TABLE IF EXISTS `categories`;
CREATE TABLE `categories`  (
  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `user_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '关联的用户ID',
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '分类名称',
  `color` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '#3498db' COMMENT '分类颜色',
  `icon` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT 'folder' COMMENT '分类图标, 默认为文件夹图标',
  `is_default` tinyint(1) NULL DEFAULT 0 COMMENT '是否为默认分类',
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of categories
-- ----------------------------
INSERT INTO `categories` VALUES ('3a51ff57-40b2-464b-9307-33d21b1911a2', '83aab7ae-9206-48c1-b6c4-51555e12f7b0', 'General', '#95a5a6', 'folder', 1, '2025-12-06 21:31:28', '2025-12-06 21:31:28');
INSERT INTO `categories` VALUES ('892af673-bfe2-4347-9fd4-f008c3d0cc05', '7f9e2932-a0d5-4df8-aaaa-166ad9b66600', '社交媒体', 'rgba(49, 199, 164, 0.79)', 'Link', 0, '2025-12-05 19:06:01', '2025-12-05 19:08:00');
INSERT INTO `categories` VALUES ('a06a19b2-ffef-44d4-9eed-730cbdec53a7', '7f9e2932-a0d5-4df8-aaaa-166ad9b66600', '游戏平台', 'rgba(115, 233, 42, 0.88)', 'Box', 0, '2025-11-17 18:42:46', '2025-11-30 23:36:13');
INSERT INTO `categories` VALUES ('b562f8d1-e879-4ec6-8236-8e2727c7a88e', 'c78efe25-f0f6-4e35-b0b5-171145ba4dca', 'General', '#95a5a6', 'folder', 1, '2025-12-04 16:42:02', '2025-12-04 16:42:02');
INSERT INTO `categories` VALUES ('b5909371-e270-46a3-86dc-1179415a38aa', 'f54ec851-b493-45da-a3a5-5bd9f64d115b', 'General', '#95a5a6', 'folder', 1, '2025-11-23 22:10:40', '2025-11-23 22:10:40');
INSERT INTO `categories` VALUES ('cd36b030-ec94-4b6a-8ca4-ccaa18c5b38b', 'de6ce1a3-ee7e-47be-ae71-794f00564fb3', 'General', '#95a5a6', 'folder', 1, '2025-12-06 21:32:20', '2025-12-06 21:32:20');
INSERT INTO `categories` VALUES ('fabb1853-fe14-4c1a-a6f5-a9afe6b86f1e', '7f9e2932-a0d5-4df8-aaaa-166ad9b66600', 'General', 'rgba(75, 135, 219, 0.82)', 'folder', 1, '2025-11-16 01:45:45', '2025-11-30 20:17:00');

-- ----------------------------
-- Table structure for Feedbacks
-- ----------------------------
DROP TABLE IF EXISTS `Feedbacks`;
CREATE TABLE `Feedbacks`  (
  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `user_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '关联的用户ID',
  `score` bigint NOT NULL COMMENT '评分数值: 1-5',
  `content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '用户的文字反馈建议',
  `app_version` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '提交反馈时的系统版本号',
  `platform` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT 'web' COMMENT '提交反馈时的平台类型',
  `createdAt` datetime NOT NULL COMMENT '提交时间',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_feedbacks_user_id`(`user_id` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '系统用户评分反馈表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of Feedbacks
-- ----------------------------

-- ----------------------------
-- Table structure for likes
-- ----------------------------
DROP TABLE IF EXISTS `likes`;
CREATE TABLE `likes`  (
  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `password_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `user_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `likes_password_id`(`password_id` ASC) USING BTREE,
  INDEX `likes_user_id`(`user_id` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of likes
-- ----------------------------
INSERT INTO `likes` VALUES ('a676ade8-3121-4cf0-b8d9-4a310353a614', '079eba6d-f748-4ce6-9782-5d85b06e7698', '7f9e2932-a0d5-4df8-aaaa-166ad9b66600', '2025-12-05 19:19:49', '2025-12-05 19:19:49');
INSERT INTO `likes` VALUES ('dc1a205e-1bd4-4356-8713-8c9cf604ff24', '1374f9ab-9810-48ba-a94b-65003f0fe805', '7f9e2932-a0d5-4df8-aaaa-166ad9b66600', '2025-12-05 19:26:48', '2025-12-05 19:26:48');

-- ----------------------------
-- Table structure for logs
-- ----------------------------
DROP TABLE IF EXISTS `logs`;
CREATE TABLE `logs`  (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `level` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `message` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `meta` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `timestamp` datetime NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 56 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of logs
-- ----------------------------
INSERT INTO `logs` VALUES (1, 'error', '服务器未知错误: log is not defined', '{\"service\":\"keyVault-log-service\",\"stack\":\"ReferenceError: log is not defined\\n    at changePassword (F:\\\\electron\\\\backend-service\\\\controllers\\\\userController.js:130:13)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}', '2025-11-17 18:35:39');
INSERT INTO `logs` VALUES (2, 'error', '服务器未知错误: Assignment to constant variable.', '{\"service\":\"keyVault-log-service\",\"stack\":\"TypeError: Assignment to constant variable.\\n    at generate (F:\\\\electron\\\\backend-service\\\\controllers\\\\passwordGeneratorController.js:47:26)\\n    at Layer.handle [as handle_request] (F:\\\\electron\\\\backend-service\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at next (F:\\\\electron\\\\backend-service\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:137:13)\\n    at Route.dispatch (F:\\\\electron\\\\backend-service\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:112:3)\\n    at Layer.handle [as handle_request] (F:\\\\electron\\\\backend-service\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at F:\\\\electron\\\\backend-service\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:281:22\\n    at Function.process_params (F:\\\\electron\\\\backend-service\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:335:12)\\n    at next (F:\\\\electron\\\\backend-service\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:275:10)\\n    at authenticate (F:\\\\electron\\\\backend-service\\\\middlewares\\\\auth.js:95:9)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}', '2025-11-17 23:14:57');
INSERT INTO `logs` VALUES (3, 'error', '服务器未知错误: Password not found', '{\"service\":\"keyVault-log-service\",\"stack\":\"Error: Password not found\\n    at F:\\\\electron\\\\backend-service\\\\routes\\\\likes.js:18:27\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}', '2025-11-23 16:56:24');
INSERT INTO `logs` VALUES (4, 'error', '服务器未知错误: Password not found', '{\"service\":\"keyVault-log-service\",\"stack\":\"Error: Password not found\\n    at collectPassword (F:\\\\electron\\\\backend-service\\\\controllers\\\\passwordController.js:694:29)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}', '2025-11-23 17:03:33');
INSERT INTO `logs` VALUES (5, 'error', '服务器未知错误: Invalid input', '{\"service\":\"keyVault-log-service\",\"stack\":\"Error: Invalid input\\n    at collectPassword (F:\\\\electron\\\\backend-service\\\\controllers\\\\passwordController.js:692:29)\\n    at Layer.handle [as handle_request] (F:\\\\electron\\\\backend-service\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at next (F:\\\\electron\\\\backend-service\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:137:13)\\n    at middleware (F:\\\\electron\\\\backend-service\\\\node_modules\\\\express-validator\\\\lib\\\\middlewares\\\\check.js:16:13)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}', '2025-11-23 17:05:58');
INSERT INTO `logs` VALUES (6, 'error', '服务器未知错误: password not found', '{\"service\":\"keyVault-log-service\",\"stack\":\"Error: password not found\\n    at collectPassword (F:\\\\electron\\\\backend-service\\\\controllers\\\\passwordController.js:703:29)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}', '2025-11-23 17:08:58');
INSERT INTO `logs` VALUES (7, 'error', '服务器未知错误: Field \'id\' doesn\'t have a default value', '{\"service\":\"keyVault-log-service\",\"name\":\"SequelizeDatabaseError\",\"parent\":{\"code\":\"ER_NO_DEFAULT_FOR_FIELD\",\"errno\":1364,\"sqlState\":\"HY000\",\"sqlMessage\":\"Field \'id\' doesn\'t have a default value\",\"sql\":\"INSERT INTO `Likes` (`id`,`passwordId`,`userId`,`createdAt`,`updatedAt`) VALUES (DEFAULT,?,?,?,?);\",\"parameters\":[\"a4848ccc-e866-41d7-abc9-009758e7812f\",\"7f9e2932-a0d5-4df8-aaaa-166ad9b66600\",\"2025-11-23 17:09:09\",\"2025-11-23 17:09:09\"]},\"original\":{\"code\":\"ER_NO_DEFAULT_FOR_FIELD\",\"errno\":1364,\"sqlState\":\"HY000\",\"sqlMessage\":\"Field \'id\' doesn\'t have a default value\",\"sql\":\"INSERT INTO `Likes` (`id`,`passwordId`,`userId`,`createdAt`,`updatedAt`) VALUES (DEFAULT,?,?,?,?);\",\"parameters\":[\"a4848ccc-e866-41d7-abc9-009758e7812f\",\"7f9e2932-a0d5-4df8-aaaa-166ad9b66600\",\"2025-11-23 17:09:09\",\"2025-11-23 17:09:09\"]},\"sql\":\"INSERT INTO `Likes` (`id`,`passwordId`,`userId`,`createdAt`,`updatedAt`) VALUES (DEFAULT,?,?,?,?);\",\"parameters\":[\"a4848ccc-e866-41d7-abc9-009758e7812f\",\"7f9e2932-a0d5-4df8-aaaa-166ad9b66600\",\"2025-11-23 17:09:09\",\"2025-11-23 17:09:09\"],\"stack\":\"Error\\n    at Query.run (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\mysql\\\\query.js:52:25)\\n    at F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:315:28\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\\n    at async MySQLQueryInterface.insert (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:308:21)\\n    at async Like.save (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:2490:35)\\n    at async Like.create (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1362:12)\\n    at async collectPassword (F:\\\\electron\\\\backend-service\\\\controllers\\\\passwordController.js:710:9)\"}', '2025-11-23 17:09:10');
INSERT INTO `logs` VALUES (8, 'error', '服务器未知错误: Cannot read properties of undefined (reading \'trim\')', '{\"service\":\"keyVault-log-service\",\"stack\":\"TypeError: Cannot read properties of undefined (reading \'trim\')\\n    at sendOk (F:\\\\electron\\\\backend-service\\\\utils\\\\response.js:34:26)\\n    at collectPassword (F:\\\\electron\\\\backend-service\\\\controllers\\\\passwordController.js:714:16)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}', '2025-11-23 17:20:49');
INSERT INTO `logs` VALUES (9, 'error', '服务器未知错误: message.trim is not a function', '{\"service\":\"keyVault-log-service\",\"stack\":\"TypeError: message.trim is not a function\\n    at sendOk (F:\\\\electron\\\\backend-service\\\\utils\\\\response.js:28:22)\\n    at collectPassword (F:\\\\electron\\\\backend-service\\\\controllers\\\\passwordController.js:710:16)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}', '2025-11-23 17:21:52');
INSERT INTO `logs` VALUES (10, 'error', '服务器未知错误: Unknown column \'UserId\' in \'field list\'', '{\"service\":\"keyVault-log-service\",\"name\":\"SequelizeDatabaseError\",\"parent\":{\"code\":\"ER_BAD_FIELD_ERROR\",\"errno\":1054,\"sqlState\":\"42S22\",\"sqlMessage\":\"Unknown column \'UserId\' in \'field list\'\",\"sql\":\"SELECT `id`, `password_id` AS `passwordId`, `user_id` AS `userId`, `createdAt`, `updatedAt`, `UserId` FROM `Likes` AS `Like` WHERE `Like`.`user_id` = \'7f9e2932-a0d5-4df8-aaaa-166ad9b66600\' AND `Like`.`password_id` = \'1374f9ab-9810-48ba-a94b-65003f0fe805\' LIMIT 1;\"},\"original\":{\"code\":\"ER_BAD_FIELD_ERROR\",\"errno\":1054,\"sqlState\":\"42S22\",\"sqlMessage\":\"Unknown column \'UserId\' in \'field list\'\",\"sql\":\"SELECT `id`, `password_id` AS `passwordId`, `user_id` AS `userId`, `createdAt`, `updatedAt`, `UserId` FROM `Likes` AS `Like` WHERE `Like`.`user_id` = \'7f9e2932-a0d5-4df8-aaaa-166ad9b66600\' AND `Like`.`password_id` = \'1374f9ab-9810-48ba-a94b-65003f0fe805\' LIMIT 1;\"},\"sql\":\"SELECT `id`, `password_id` AS `passwordId`, `user_id` AS `userId`, `createdAt`, `updatedAt`, `UserId` FROM `Likes` AS `Like` WHERE `Like`.`user_id` = \'7f9e2932-a0d5-4df8-aaaa-166ad9b66600\' AND `Like`.`password_id` = \'1374f9ab-9810-48ba-a94b-65003f0fe805\' LIMIT 1;\",\"parameters\":{},\"stack\":\"Error\\n    at Query.run (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\mysql\\\\query.js:52:25)\\n    at F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:315:28\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\\n    at async MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:12)\\n    at async Like.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:21)\\n    at async Like.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\\n    at async collectPassword (F:\\\\electron\\\\backend-service\\\\controllers\\\\passwordController.js:705:20)\"}', '2025-11-23 20:12:22');
INSERT INTO `logs` VALUES (11, 'error', '服务器未知错误: Unknown column \'UserId\' in \'field list\'', '{\"service\":\"keyVault-log-service\",\"name\":\"SequelizeDatabaseError\",\"parent\":{\"code\":\"ER_BAD_FIELD_ERROR\",\"errno\":1054,\"sqlState\":\"42S22\",\"sqlMessage\":\"Unknown column \'UserId\' in \'field list\'\",\"sql\":\"SELECT `id`, `password_id` AS `passwordId`, `user_id` AS `userId`, `createdAt`, `updatedAt`, `UserId` FROM `Likes` AS `Like` WHERE `Like`.`user_id` = \'7f9e2932-a0d5-4df8-aaaa-166ad9b66600\' AND `Like`.`password_id` = \'1374f9ab-9810-48ba-a94b-65003f0fe805\' LIMIT 1;\"},\"original\":{\"code\":\"ER_BAD_FIELD_ERROR\",\"errno\":1054,\"sqlState\":\"42S22\",\"sqlMessage\":\"Unknown column \'UserId\' in \'field list\'\",\"sql\":\"SELECT `id`, `password_id` AS `passwordId`, `user_id` AS `userId`, `createdAt`, `updatedAt`, `UserId` FROM `Likes` AS `Like` WHERE `Like`.`user_id` = \'7f9e2932-a0d5-4df8-aaaa-166ad9b66600\' AND `Like`.`password_id` = \'1374f9ab-9810-48ba-a94b-65003f0fe805\' LIMIT 1;\"},\"sql\":\"SELECT `id`, `password_id` AS `passwordId`, `user_id` AS `userId`, `createdAt`, `updatedAt`, `UserId` FROM `Likes` AS `Like` WHERE `Like`.`user_id` = \'7f9e2932-a0d5-4df8-aaaa-166ad9b66600\' AND `Like`.`password_id` = \'1374f9ab-9810-48ba-a94b-65003f0fe805\' LIMIT 1;\",\"parameters\":{},\"stack\":\"Error\\n    at Query.run (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\mysql\\\\query.js:52:25)\\n    at F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:315:28\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\\n    at async MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:12)\\n    at async Like.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:21)\\n    at async Like.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\\n    at async collectPassword (F:\\\\electron\\\\backend-service\\\\controllers\\\\passwordController.js:705:20)\"}', '2025-11-23 20:12:53');
INSERT INTO `logs` VALUES (12, 'error', '服务器未知错误: Unknown column \'UserId\' in \'field list\'', '{\"service\":\"keyVault-log-service\",\"name\":\"SequelizeDatabaseError\",\"parent\":{\"code\":\"ER_BAD_FIELD_ERROR\",\"errno\":1054,\"sqlState\":\"42S22\",\"sqlMessage\":\"Unknown column \'UserId\' in \'field list\'\",\"sql\":\"SELECT `id`, `password_id` AS `passwordId`, `user_id` AS `userId`, `createdAt`, `updatedAt`, `UserId` FROM `Likes` AS `Like` WHERE `Like`.`user_id` = \'7f9e2932-a0d5-4df8-aaaa-166ad9b66600\' AND `Like`.`password_id` = \'a4848ccc-e866-41d7-abc9-009758e7812f\' LIMIT 1;\"},\"original\":{\"code\":\"ER_BAD_FIELD_ERROR\",\"errno\":1054,\"sqlState\":\"42S22\",\"sqlMessage\":\"Unknown column \'UserId\' in \'field list\'\",\"sql\":\"SELECT `id`, `password_id` AS `passwordId`, `user_id` AS `userId`, `createdAt`, `updatedAt`, `UserId` FROM `Likes` AS `Like` WHERE `Like`.`user_id` = \'7f9e2932-a0d5-4df8-aaaa-166ad9b66600\' AND `Like`.`password_id` = \'a4848ccc-e866-41d7-abc9-009758e7812f\' LIMIT 1;\"},\"sql\":\"SELECT `id`, `password_id` AS `passwordId`, `user_id` AS `userId`, `createdAt`, `updatedAt`, `UserId` FROM `Likes` AS `Like` WHERE `Like`.`user_id` = \'7f9e2932-a0d5-4df8-aaaa-166ad9b66600\' AND `Like`.`password_id` = \'a4848ccc-e866-41d7-abc9-009758e7812f\' LIMIT 1;\",\"parameters\":{},\"stack\":\"Error\\n    at Query.run (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\mysql\\\\query.js:52:25)\\n    at F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:315:28\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\\n    at async MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:12)\\n    at async Like.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:21)\\n    at async Like.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\\n    at async collectPassword (F:\\\\electron\\\\backend-service\\\\controllers\\\\passwordController.js:705:20)\"}', '2025-11-23 20:14:05');
INSERT INTO `logs` VALUES (13, 'error', '服务器未知错误: password not found', '{\"service\":\"keyVault-log-service\",\"stack\":\"Error: password not found\\n    at collectPassword (F:\\\\electron\\\\backend-service\\\\controllers\\\\passwordController.js:703:29)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}', '2025-11-23 20:15:45');
INSERT INTO `logs` VALUES (14, 'error', '服务器未知错误: Unknown column \'UserId\' in \'field list\'', '{\"service\":\"keyVault-log-service\",\"name\":\"SequelizeDatabaseError\",\"parent\":{\"code\":\"ER_BAD_FIELD_ERROR\",\"errno\":1054,\"sqlState\":\"42S22\",\"sqlMessage\":\"Unknown column \'UserId\' in \'field list\'\",\"sql\":\"SELECT `id`, `password_id` AS `passwordId`, `user_id` AS `userId`, `createdAt`, `updatedAt`, `UserId` FROM `Likes` AS `Like` WHERE `Like`.`user_id` = \'7f9e2932-a0d5-4df8-aaaa-166ad9b66600\' AND `Like`.`password_id` = \'a4848ccc-e866-41d7-abc9-009758e7812f\' LIMIT 1;\"},\"original\":{\"code\":\"ER_BAD_FIELD_ERROR\",\"errno\":1054,\"sqlState\":\"42S22\",\"sqlMessage\":\"Unknown column \'UserId\' in \'field list\'\",\"sql\":\"SELECT `id`, `password_id` AS `passwordId`, `user_id` AS `userId`, `createdAt`, `updatedAt`, `UserId` FROM `Likes` AS `Like` WHERE `Like`.`user_id` = \'7f9e2932-a0d5-4df8-aaaa-166ad9b66600\' AND `Like`.`password_id` = \'a4848ccc-e866-41d7-abc9-009758e7812f\' LIMIT 1;\"},\"sql\":\"SELECT `id`, `password_id` AS `passwordId`, `user_id` AS `userId`, `createdAt`, `updatedAt`, `UserId` FROM `Likes` AS `Like` WHERE `Like`.`user_id` = \'7f9e2932-a0d5-4df8-aaaa-166ad9b66600\' AND `Like`.`password_id` = \'a4848ccc-e866-41d7-abc9-009758e7812f\' LIMIT 1;\",\"parameters\":{},\"stack\":\"Error\\n    at Query.run (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\mysql\\\\query.js:52:25)\\n    at F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:315:28\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\\n    at async MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:12)\\n    at async Like.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:21)\\n    at async Like.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\\n    at async collectPassword (F:\\\\electron\\\\backend-service\\\\controllers\\\\passwordController.js:705:20)\"}', '2025-11-23 20:15:54');
INSERT INTO `logs` VALUES (15, 'warn', '只允许上传图片。仅用于演示，实际项目中请根据需求调整。', '{\"service\":\"keyVault-log-service\"}', '2025-11-23 21:37:31');
INSERT INTO `logs` VALUES (16, 'error', '服务器未知错误: \"arguments[3]\" must be of type \"string | Buffer\", got number instead.', '{\"service\":\"keyVault-log-service\",\"stack\":\"TypeError: \\\"arguments[3]\\\" must be of type \\\"string | Buffer\\\", got number instead.\\n    at encodeCommand (F:\\\\electron\\\\backend-service\\\\node_modules\\\\@redis\\\\client\\\\dist\\\\lib\\\\RESP\\\\encoder.js:17:19)\\n    at RedisCommandsQueue.commandsToWrite (F:\\\\electron\\\\backend-service\\\\node_modules\\\\@redis\\\\client\\\\dist\\\\lib\\\\client\\\\commands-queue.js:340:49)\\n    at commandsToWrite.next (<anonymous>)\\n    at RedisSocket.write (F:\\\\electron\\\\backend-service\\\\node_modules\\\\@redis\\\\client\\\\dist\\\\lib\\\\client\\\\socket.js:243:20)\\n    at #write (F:\\\\electron\\\\backend-service\\\\node_modules\\\\@redis\\\\client\\\\dist\\\\lib\\\\client\\\\index.js:713:22)\\n    at Immediate.<anonymous> (F:\\\\electron\\\\backend-service\\\\node_modules\\\\@redis\\\\client\\\\dist\\\\lib\\\\client\\\\index.js:720:24)\\n    at process.processImmediate (node:internal/timers:485:21)\"}', '2025-11-23 21:51:56');
INSERT INTO `logs` VALUES (17, 'error', '服务器未知错误: Cannot read properties of undefined (reading \'connect\')', '{\"service\":\"keyVault-log-service\",\"stack\":\"TypeError: Cannot read properties of undefined (reading \'connect\')\\n    at get (F:\\\\electron\\\\backend-service\\\\services\\\\redisService.js:72:20)\\n    at validateCaptcha (F:\\\\electron\\\\backend-service\\\\middlewares\\\\validation.js:16:27)\\n    at Layer.handle [as handle_request] (F:\\\\electron\\\\backend-service\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at next (F:\\\\electron\\\\backend-service\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:137:13)\\n    at middleware (F:\\\\electron\\\\backend-service\\\\node_modules\\\\express-validator\\\\lib\\\\middlewares\\\\check.js:16:13)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}', '2025-11-23 22:01:22');
INSERT INTO `logs` VALUES (18, 'error', '服务器未知错误: Cannot read properties of undefined (reading \'client\')', '{\"service\":\"keyVault-log-service\",\"stack\":\"TypeError: Cannot read properties of undefined (reading \'client\')\\n    at get (F:\\\\electron\\\\backend-service\\\\services\\\\redisService.js:73:17)\\n    at validateCaptcha (F:\\\\electron\\\\backend-service\\\\middlewares\\\\validation.js:16:27)\\n    at Layer.handle [as handle_request] (F:\\\\electron\\\\backend-service\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at next (F:\\\\electron\\\\backend-service\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:137:13)\\n    at middleware (F:\\\\electron\\\\backend-service\\\\node_modules\\\\express-validator\\\\lib\\\\middlewares\\\\check.js:16:13)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}', '2025-11-23 22:02:50');
INSERT INTO `logs` VALUES (19, 'error', '服务器未知错误: Cannot read properties of undefined (reading \'connect\')', '{\"service\":\"keyVault-log-service\",\"stack\":\"TypeError: Cannot read properties of undefined (reading \'connect\')\\n    at get (F:\\\\electron\\\\backend-service\\\\services\\\\redisService.js:72:16)\\n    at validateCaptcha (F:\\\\electron\\\\backend-service\\\\middlewares\\\\validation.js:16:27)\\n    at Layer.handle [as handle_request] (F:\\\\electron\\\\backend-service\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at next (F:\\\\electron\\\\backend-service\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:137:13)\\n    at middleware (F:\\\\electron\\\\backend-service\\\\node_modules\\\\express-validator\\\\lib\\\\middlewares\\\\check.js:16:13)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}', '2025-11-23 22:03:25');
INSERT INTO `logs` VALUES (20, 'error', '服务器未知错误: Operation timeout', '{\"service\":\"keyVault-log-service\",\"name\":\"SequelizeConnectionAcquireTimeoutError\",\"parent\":{},\"original\":{},\"stack\":\"SequelizeConnectionAcquireTimeoutError: Operation timeout\\n    at ConnectionManager.getConnection (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\connection-manager.js:206:15)\\n    at async F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:305:26\\n    at async MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:12)\\n    at async User.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:21)\\n    at async User.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\\n    at async login (F:\\\\electron\\\\backend-service\\\\controllers\\\\authController.js:143:20)\"}', '2025-11-28 14:40:34');
INSERT INTO `logs` VALUES (21, 'error', '服务器未知错误: Operation timeout', '{\"service\":\"keyVault-log-service\",\"name\":\"SequelizeConnectionAcquireTimeoutError\",\"parent\":{},\"original\":{},\"stack\":\"SequelizeConnectionAcquireTimeoutError: Operation timeout\\n    at ConnectionManager.getConnection (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\connection-manager.js:206:15)\\n    at async F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:305:26\\n    at async MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:12)\\n    at async User.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:21)\\n    at async User.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\\n    at async login (F:\\\\electron\\\\backend-service\\\\controllers\\\\authController.js:143:20)\"}', '2025-11-28 14:42:31');
INSERT INTO `logs` VALUES (22, 'error', '服务器未知错误: Operation timeout', '{\"service\":\"keyVault-log-service\",\"name\":\"SequelizeConnectionAcquireTimeoutError\",\"parent\":{},\"original\":{},\"stack\":\"SequelizeConnectionAcquireTimeoutError: Operation timeout\\n    at ConnectionManager.getConnection (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\connection-manager.js:206:15)\\n    at async F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:305:26\\n    at async MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:12)\\n    at async User.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:21)\\n    at async User.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\\n    at async login (F:\\\\electron\\\\backend-service\\\\controllers\\\\authController.js:143:20)\"}', '2025-11-28 14:44:32');
INSERT INTO `logs` VALUES (23, 'error', '服务器未知错误: Operation timeout', '{\"service\":\"keyVault-log-service\",\"name\":\"SequelizeConnectionAcquireTimeoutError\",\"parent\":{},\"original\":{},\"stack\":\"SequelizeConnectionAcquireTimeoutError: Operation timeout\\n    at ConnectionManager.getConnection (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\connection-manager.js:206:15)\\n    at async F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:305:26\\n    at async MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:12)\\n    at async User.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:21)\\n    at async User.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\\n    at async login (F:\\\\electron\\\\backend-service\\\\controllers\\\\authController.js:143:20)\"}', '2025-11-29 17:04:53');
INSERT INTO `logs` VALUES (24, 'error', '服务器未知错误: Operation timeout', '{\"service\":\"keyVault-log-service\",\"name\":\"SequelizeConnectionAcquireTimeoutError\",\"parent\":{},\"original\":{},\"stack\":\"SequelizeConnectionAcquireTimeoutError: Operation timeout\\n    at ConnectionManager.getConnection (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\connection-manager.js:206:15)\\n    at async F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:305:26\\n    at async MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:12)\\n    at async User.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:21)\\n    at async User.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\\n    at async login (F:\\\\electron\\\\backend-service\\\\controllers\\\\authController.js:143:20)\"}', '2025-11-29 17:15:53');
INSERT INTO `logs` VALUES (25, 'error', '服务器未知错误: Operation timeout', '{\"service\":\"keyVault-log-service\",\"name\":\"SequelizeConnectionAcquireTimeoutError\",\"parent\":{},\"original\":{},\"stack\":\"SequelizeConnectionAcquireTimeoutError: Operation timeout\\n    at ConnectionManager.getConnection (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\connection-manager.js:206:15)\\n    at async F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:305:26\\n    at async MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:12)\\n    at async User.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:21)\\n    at async User.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\\n    at async login (F:\\\\electron\\\\backend-service\\\\controllers\\\\authController.js:143:20)\"}', '2025-11-29 17:16:53');
INSERT INTO `logs` VALUES (26, 'error', '服务器未知错误: ConnectionManager.getConnection was called after the connection manager was closed!', '{\"service\":\"keyVault-log-service\",\"stack\":\"Error: ConnectionManager.getConnection was called after the connection manager was closed!\\n    at ConnectionManager.getConnection (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\connection-manager.js:70:13)\\n    at F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:305:111\\n    at F:\\\\electron\\\\backend-service\\\\node_modules\\\\retry-as-promised\\\\dist\\\\index.js:65:25\\n    at new Promise (<anonymous>)\\n    at retryAsPromised (F:\\\\electron\\\\backend-service\\\\node_modules\\\\retry-as-promised\\\\dist\\\\index.js:54:12)\\n    at Sequelize.query (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:300:12)\\n    at MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:33)\\n    at User.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:47)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\\n    at async User.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\"}', '2025-11-29 17:16:53');
INSERT INTO `logs` VALUES (27, 'error', '服务器未知错误: ConnectionManager.getConnection was called after the connection manager was closed!', '{\"service\":\"keyVault-log-service\",\"stack\":\"Error: ConnectionManager.getConnection was called after the connection manager was closed!\\n    at ConnectionManager.getConnection (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\connection-manager.js:70:13)\\n    at F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:305:111\\n    at F:\\\\electron\\\\backend-service\\\\node_modules\\\\retry-as-promised\\\\dist\\\\index.js:65:25\\n    at new Promise (<anonymous>)\\n    at retryAsPromised (F:\\\\electron\\\\backend-service\\\\node_modules\\\\retry-as-promised\\\\dist\\\\index.js:54:12)\\n    at Sequelize.query (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:300:12)\\n    at MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:33)\\n    at User.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:47)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\\n    at async User.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\"}', '2025-11-29 17:16:53');
INSERT INTO `logs` VALUES (28, 'error', '服务器未知错误: Operation timeout', '{\"service\":\"keyVault-log-service\",\"name\":\"SequelizeConnectionAcquireTimeoutError\",\"parent\":{},\"original\":{},\"stack\":\"SequelizeConnectionAcquireTimeoutError: Operation timeout\\n    at ConnectionManager.getConnection (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\connection-manager.js:206:15)\\n    at async F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:305:26\\n    at async MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:12)\\n    at async User.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:21)\\n    at async User.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\\n    at async login (F:\\\\electron\\\\backend-service\\\\controllers\\\\authController.js:143:20)\"}', '2025-11-29 17:27:48');
INSERT INTO `logs` VALUES (29, 'error', '服务器未知错误: Operation timeout', '{\"service\":\"keyVault-log-service\",\"name\":\"SequelizeConnectionAcquireTimeoutError\",\"parent\":{},\"original\":{},\"stack\":\"SequelizeConnectionAcquireTimeoutError: Operation timeout\\n    at ConnectionManager.getConnection (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\connection-manager.js:206:15)\\n    at runNextTicks (node:internal/process/task_queues:65:5)\\n    at process.processTimers (node:internal/timers:520:9)\\n    at async F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:305:26\\n    at async MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:12)\\n    at async User.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:21)\\n    at async User.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\\n    at async login (F:\\\\electron\\\\backend-service\\\\controllers\\\\authController.js:143:20)\"}', '2025-11-29 17:51:00');
INSERT INTO `logs` VALUES (30, 'error', '服务器未知错误: Operation timeout', '{\"service\":\"keyVault-log-service\",\"name\":\"SequelizeConnectionAcquireTimeoutError\",\"parent\":{},\"original\":{},\"stack\":\"SequelizeConnectionAcquireTimeoutError: Operation timeout\\n    at ConnectionManager.getConnection (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\connection-manager.js:206:15)\\n    at async F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:305:26\\n    at async MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:12)\\n    at async User.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:21)\\n    at async User.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\\n    at async login (F:\\\\electron\\\\backend-service\\\\controllers\\\\authController.js:143:20)\"}', '2025-11-29 18:06:27');
INSERT INTO `logs` VALUES (31, 'error', '服务器未知错误: Operation timeout', '{\"service\":\"keyVault-log-service\",\"name\":\"SequelizeConnectionAcquireTimeoutError\",\"parent\":{},\"original\":{},\"stack\":\"SequelizeConnectionAcquireTimeoutError: Operation timeout\\n    at ConnectionManager.getConnection (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\connection-manager.js:206:15)\\n    at async F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:305:26\\n    at async MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:12)\\n    at async User.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:21)\\n    at async User.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\\n    at async login (F:\\\\electron\\\\backend-service\\\\controllers\\\\authController.js:143:20)\"}', '2025-11-29 18:13:23');
INSERT INTO `logs` VALUES (32, 'error', '服务器未知错误: Operation timeout', '{\"service\":\"keyVault-log-service\",\"name\":\"SequelizeConnectionAcquireTimeoutError\",\"parent\":{},\"original\":{},\"stack\":\"SequelizeConnectionAcquireTimeoutError: Operation timeout\\n    at ConnectionManager.getConnection (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\connection-manager.js:206:15)\\n    at async F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:305:26\\n    at async MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:12)\\n    at async User.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:21)\\n    at async User.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\\n    at async login (F:\\\\electron\\\\backend-service\\\\controllers\\\\authController.js:143:20)\"}', '2025-11-29 18:30:20');
INSERT INTO `logs` VALUES (33, 'error', '服务器未知错误: ConnectionManager.getConnection was called after the connection manager was closed!', '{\"service\":\"keyVault-log-service\",\"stack\":\"Error: ConnectionManager.getConnection was called after the connection manager was closed!\\n    at ConnectionManager.getConnection (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\connection-manager.js:70:13)\\n    at F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:305:111\\n    at F:\\\\electron\\\\backend-service\\\\node_modules\\\\retry-as-promised\\\\dist\\\\index.js:65:25\\n    at new Promise (<anonymous>)\\n    at retryAsPromised (F:\\\\electron\\\\backend-service\\\\node_modules\\\\retry-as-promised\\\\dist\\\\index.js:54:12)\\n    at Sequelize.query (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:300:12)\\n    at MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:33)\\n    at User.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:47)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\\n    at async User.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\"}', '2025-11-29 18:30:20');
INSERT INTO `logs` VALUES (34, 'error', '服务器未知错误: Decryption failed. Incorrect master password or corrupted data.', '{\"service\":\"keyVault-log-service\",\"stack\":\"Error: Decryption failed. Incorrect master password or corrupted data.\\n    at decrypt (F:\\\\electron\\\\backend-service\\\\services\\\\encryptionService.js:102:19)\\n    at F:\\\\electron\\\\backend-service\\\\controllers\\\\passwordController.js:168:37\\n    at Array.map (<anonymous>)\\n    at getAll (F:\\\\electron\\\\backend-service\\\\controllers\\\\passwordController.js:167:14)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}', '2025-11-29 19:59:08');
INSERT INTO `logs` VALUES (35, 'error', '服务器未知错误: Decryption failed. Incorrect master password or corrupted data.', '{\"service\":\"keyVault-log-service\",\"stack\":\"Error: Decryption failed. Incorrect master password or corrupted data.\\n    at decrypt (F:\\\\electron\\\\backend-service\\\\services\\\\encryptionService.js:102:19)\\n    at F:\\\\electron\\\\backend-service\\\\controllers\\\\passwordController.js:168:37\\n    at Array.map (<anonymous>)\\n    at getAll (F:\\\\electron\\\\backend-service\\\\controllers\\\\passwordController.js:167:14)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}', '2025-11-29 19:59:36');
INSERT INTO `logs` VALUES (36, 'error', '服务器未知错误: Decryption failed. Incorrect master password or corrupted data.', '{\"service\":\"keyVault-log-service\",\"stack\":\"Error: Decryption failed. Incorrect master password or corrupted data.\\n    at decrypt (F:\\\\electron\\\\backend-service\\\\services\\\\encryptionService.js:102:19)\\n    at F:\\\\electron\\\\backend-service\\\\controllers\\\\passwordController.js:168:37\\n    at Array.map (<anonymous>)\\n    at getAll (F:\\\\electron\\\\backend-service\\\\controllers\\\\passwordController.js:167:14)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}', '2025-11-29 20:00:42');
INSERT INTO `logs` VALUES (37, 'error', '服务器未知错误: limit is not defined', '{\"service\":\"keyVault-log-service\",\"stack\":\"ReferenceError: limit is not defined\\n    at getAll (F:\\\\electron\\\\backend-service\\\\controllers\\\\passwordController.js:172:25)\\n    at Layer.handle [as handle_request] (F:\\\\electron\\\\backend-service\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at next (F:\\\\electron\\\\backend-service\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:137:13)\\n    at middleware (F:\\\\electron\\\\backend-service\\\\node_modules\\\\express-validator\\\\lib\\\\middlewares\\\\check.js:16:13)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}', '2025-11-29 22:07:24');
INSERT INTO `logs` VALUES (38, 'error', '服务器未知错误: Operation timeout', '{\"service\":\"keyVault-log-service\",\"name\":\"SequelizeConnectionAcquireTimeoutError\",\"parent\":{},\"original\":{},\"stack\":\"SequelizeConnectionAcquireTimeoutError: Operation timeout\\n    at ConnectionManager.getConnection (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\connection-manager.js:206:15)\\n    at async F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:305:26\\n    at async MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:12)\\n    at async User.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:21)\\n    at async User.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\\n    at async login (F:\\\\electron\\\\backend-service\\\\controllers\\\\authController.js:143:20)\"}', '2025-12-02 15:57:42');
INSERT INTO `logs` VALUES (39, 'error', '服务器未知错误: ConnectionManager.getConnection was called after the connection manager was closed!', '{\"service\":\"keyVault-log-service\",\"stack\":\"Error: ConnectionManager.getConnection was called after the connection manager was closed!\\n    at ConnectionManager.getConnection (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\connection-manager.js:70:13)\\n    at F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:305:111\\n    at F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\retry-as-promised@7.1.1\\\\node_modules\\\\retry-as-promised\\\\dist\\\\index.js:65:25\\n    at new Promise (<anonymous>)\\n    at retryAsPromised (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\retry-as-promised@7.1.1\\\\node_modules\\\\retry-as-promised\\\\dist\\\\index.js:54:12)\\n    at Sequelize.query (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:300:12)\\n    at MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:33)\\n    at User.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:47)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\\n    at async User.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\"}', '2025-12-02 15:57:42');
INSERT INTO `logs` VALUES (40, 'error', '服务器未知错误: Cannot read properties of undefined (reading \'id\')', '{\"service\":\"keyVault-log-service\",\"stack\":\"TypeError: Cannot read properties of undefined (reading \'id\')\\n    at logout (F:\\\\electron\\\\backend-service\\\\controllers\\\\authController.js:286:31)\\n    at Layer.handle [as handle_request] (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at next (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:137:13)\\n    at Route.dispatch (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:112:3)\\n    at Layer.handle [as handle_request] (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:281:22\\n    at Function.process_params (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:335:12)\\n    at next (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:275:10)\\n    at Function.handle (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:174:3)\\n    at router (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:47:12)\"}', '2025-12-03 10:53:55');
INSERT INTO `logs` VALUES (41, 'error', '服务器未知错误: Cannot read properties of undefined (reading \'id\')', '{\"service\":\"keyVault-log-service\",\"stack\":\"TypeError: Cannot read properties of undefined (reading \'id\')\\n    at logout (F:\\\\electron\\\\backend-service\\\\controllers\\\\authController.js:286:31)\\n    at Layer.handle [as handle_request] (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at next (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:137:13)\\n    at Route.dispatch (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:112:3)\\n    at Layer.handle [as handle_request] (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:281:22\\n    at Function.process_params (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:335:12)\\n    at next (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:275:10)\\n    at Function.handle (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:174:3)\\n    at router (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:47:12)\"}', '2025-12-03 10:53:55');
INSERT INTO `logs` VALUES (42, 'error', '服务器未知错误: Cannot read properties of undefined (reading \'id\')', '{\"service\":\"keyVault-log-service\",\"stack\":\"TypeError: Cannot read properties of undefined (reading \'id\')\\n    at logout (F:\\\\electron\\\\backend-service\\\\controllers\\\\authController.js:286:31)\\n    at Layer.handle [as handle_request] (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at next (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:137:13)\\n    at Route.dispatch (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:112:3)\\n    at Layer.handle [as handle_request] (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:281:22\\n    at Function.process_params (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:335:12)\\n    at next (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:275:10)\\n    at Function.handle (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:174:3)\\n    at router (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:47:12)\"}', '2025-12-03 10:56:11');
INSERT INTO `logs` VALUES (43, 'error', '服务器未知错误: Cannot read properties of undefined (reading \'id\')', '{\"service\":\"keyVault-log-service\",\"stack\":\"TypeError: Cannot read properties of undefined (reading \'id\')\\n    at logout (F:\\\\electron\\\\backend-service\\\\controllers\\\\authController.js:286:31)\\n    at Layer.handle [as handle_request] (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at next (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:137:13)\\n    at Route.dispatch (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:112:3)\\n    at Layer.handle [as handle_request] (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:281:22\\n    at Function.process_params (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:335:12)\\n    at next (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:275:10)\\n    at Function.handle (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:174:3)\\n    at router (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:47:12)\"}', '2025-12-03 10:56:11');
INSERT INTO `logs` VALUES (44, 'error', '服务器未知错误: Cannot read properties of undefined (reading \'id\')', '{\"service\":\"keyVault-log-service\",\"stack\":\"TypeError: Cannot read properties of undefined (reading \'id\')\\n    at logout (F:\\\\electron\\\\backend-service\\\\controllers\\\\authController.js:286:31)\\n    at Layer.handle [as handle_request] (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at next (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:137:13)\\n    at Route.dispatch (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\route.js:112:3)\\n    at Layer.handle [as handle_request] (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\layer.js:95:5)\\n    at F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:281:22\\n    at Function.process_params (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:335:12)\\n    at next (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:275:10)\\n    at Function.handle (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:174:3)\\n    at router (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\express@4.16.4\\\\node_modules\\\\express\\\\lib\\\\router\\\\index.js:47:12)\"}', '2025-12-03 10:56:52');
INSERT INTO `logs` VALUES (45, 'error', '服务器未知错误: Operation timeout', '{\"service\":\"keyVault-log-service\",\"name\":\"SequelizeConnectionAcquireTimeoutError\",\"parent\":{},\"original\":{},\"stack\":\"SequelizeConnectionAcquireTimeoutError: Operation timeout\\n    at ConnectionManager.getConnection (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\connection-manager.js:206:15)\\n    at async F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:305:26\\n    at async MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:12)\\n    at async User.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:21)\\n    at async User.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\\n    at async login (F:\\\\electron\\\\backend-service\\\\controllers\\\\authController.js:143:20)\"}', '2025-12-03 10:58:02');
INSERT INTO `logs` VALUES (46, 'error', '服务器未知错误: Operation timeout', '{\"service\":\"keyVault-log-service\",\"name\":\"SequelizeConnectionAcquireTimeoutError\",\"parent\":{},\"original\":{},\"stack\":\"SequelizeConnectionAcquireTimeoutError: Operation timeout\\n    at ConnectionManager.getConnection (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\connection-manager.js:206:15)\\n    at async F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:305:26\\n    at async MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:12)\\n    at async User.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:21)\\n    at async User.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\\n    at async login (F:\\\\electron\\\\backend-service\\\\controllers\\\\authController.js:143:20)\"}', '2025-12-03 12:00:24');
INSERT INTO `logs` VALUES (47, 'error', '服务器未知错误: 缺少或格式不正确的认证信息', '{\"service\":\"keyVault-log-service\",\"statusCode\":400}', '2025-12-03 12:05:30');
INSERT INTO `logs` VALUES (48, 'error', '服务器未知错误: 缺少或格式不正确的认证信息', '{\"service\":\"keyVault-log-service\",\"statusCode\":400}', '2025-12-03 12:05:59');
INSERT INTO `logs` VALUES (49, 'error', '服务器未知错误: Operation timeout', '{\"service\":\"keyVault-log-service\",\"name\":\"SequelizeConnectionAcquireTimeoutError\",\"parent\":{},\"original\":{},\"stack\":\"SequelizeConnectionAcquireTimeoutError: Operation timeout\\n    at ConnectionManager.getConnection (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\connection-manager.js:206:15)\\n    at async F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:305:26\\n    at async MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:12)\\n    at async User.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:21)\\n    at async User.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\\n    at async login (F:\\\\electron\\\\backend-service\\\\controllers\\\\authController.js:143:20)\"}', '2025-12-03 18:29:39');
INSERT INTO `logs` VALUES (50, 'error', '服务器未知错误: Operation timeout', '{\"service\":\"keyVault-log-service\",\"name\":\"SequelizeConnectionAcquireTimeoutError\",\"parent\":{},\"original\":{},\"stack\":\"SequelizeConnectionAcquireTimeoutError: Operation timeout\\n    at ConnectionManager.getConnection (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\connection-manager.js:206:15)\\n    at async F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:305:26\\n    at async MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:12)\\n    at async User.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:21)\\n    at async User.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\\n    at async login (F:\\\\electron\\\\backend-service\\\\controllers\\\\authController.js:143:20)\"}', '2025-12-04 14:48:07');
INSERT INTO `logs` VALUES (51, 'error', '服务器未知错误: Operation timeout', '{\"service\":\"keyVault-log-service\",\"name\":\"SequelizeConnectionAcquireTimeoutError\",\"parent\":{},\"original\":{},\"stack\":\"SequelizeConnectionAcquireTimeoutError: Operation timeout\\n    at ConnectionManager.getConnection (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\connection-manager.js:206:15)\\n    at async F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:305:26\\n    at async MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:12)\\n    at async User.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:21)\\n    at async User.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\\n    at async User.findByPk (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1221:12)\\n    at async authenticate (F:\\\\electron\\\\backend-service\\\\middlewares\\\\auth.js:48:18)\"}', '2025-12-04 14:53:26');
INSERT INTO `logs` VALUES (52, 'error', '服务器未知错误: Operation timeout', '{\"service\":\"keyVault-log-service\",\"name\":\"SequelizeConnectionAcquireTimeoutError\",\"parent\":{},\"original\":{},\"stack\":\"SequelizeConnectionAcquireTimeoutError: Operation timeout\\n    at ConnectionManager.getConnection (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\connection-manager.js:206:15)\\n    at async F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:305:26\\n    at async MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:12)\\n    at async User.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:21)\\n    at async User.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\\n    at async User.findByPk (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1221:12)\\n    at async authenticate (F:\\\\electron\\\\backend-service\\\\middlewares\\\\auth.js:48:18)\"}', '2025-12-04 14:54:09');
INSERT INTO `logs` VALUES (53, 'error', '服务器未知错误: Operation timeout', '{\"service\":\"keyVault-log-service\",\"name\":\"SequelizeConnectionAcquireTimeoutError\",\"parent\":{},\"original\":{},\"stack\":\"SequelizeConnectionAcquireTimeoutError: Operation timeout\\n    at ConnectionManager.getConnection (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\connection-manager.js:206:15)\\n    at async F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\sequelize.js:305:26\\n    at async MySQLQueryInterface.select (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\dialects\\\\abstract\\\\query-interface.js:407:12)\\n    at async User.findAll (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1140:21)\\n    at async User.findOne (F:\\\\electron\\\\backend-service\\\\node_modules\\\\.pnpm\\\\sequelize@6.37.7_mysql2@3.15.3\\\\node_modules\\\\sequelize\\\\lib\\\\model.js:1240:12)\\n    at async changePassword (F:\\\\electron\\\\backend-service\\\\controllers\\\\userController.js:245:20)\"}', '2025-12-04 14:57:04');
INSERT INTO `logs` VALUES (54, 'error', '服务器未知错误: Cannot read properties of null (reading \'destroy\')', '{\"service\":\"keyVault-log-service\",\"stack\":\"TypeError: Cannot read properties of null (reading \'destroy\')\\n    at login (F:\\\\electron\\\\backend-service\\\\controllers\\\\authController.js:250:29)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}', '2025-12-05 16:42:15');
INSERT INTO `logs` VALUES (55, 'error', '服务器未知错误: parsedIsActive is not defined', '{\"service\":\"keyVault-log-service\",\"stack\":\"ReferenceError: parsedIsActive is not defined\\n    at toggleUserStatus (F:\\\\electron\\\\backend-service\\\\controllers\\\\adminController.js:191:9)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\"}', '2025-12-06 21:24:02');

-- ----------------------------
-- Table structure for passwordhistories
-- ----------------------------
DROP TABLE IF EXISTS `passwordhistories`;
CREATE TABLE `passwordhistories`  (
  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `password_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `encrypted_password` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `changed_at` datetime NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `fk_password_history_password_id`(`password_id` ASC) USING BTREE,
  CONSTRAINT `fk_password_history_password_id` FOREIGN KEY (`password_id`) REFERENCES `passwords` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of passwordhistories
-- ----------------------------

-- ----------------------------
-- Table structure for Passwords
-- ----------------------------
DROP TABLE IF EXISTS `Passwords`;
CREATE TABLE `Passwords`  (
  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `user_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '关联的用户ID',
  `category_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '关联的分类ID',
  `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '密码所属应用名称',
  `username` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '应用登录用户名',
  `encrypted_password` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '加密后的密码',
  `url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '应用网址',
  `notes` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '备注信息',
  `is_favorite` tinyint(1) NULL DEFAULT 0 COMMENT '是否为收藏',
  `deletedAt` datetime NULL DEFAULT NULL,
  `custom_fields` json NULL COMMENT '自定义字段',
  `password_strength` int NULL DEFAULT 0 COMMENT '密码强度',
  `last_used` datetime NULL DEFAULT NULL COMMENT '最后一次使用时间',
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `passwords_deleted_at`(`deletedAt` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of Passwords
-- ----------------------------
INSERT INTO `Passwords` VALUES ('079eba6d-f748-4ce6-9782-5d85b06e7698', '7f9e2932-a0d5-4df8-aaaa-166ad9b66600', 'a06a19b2-ffef-44d4-9eed-730cbdec53a7', 'Facebook', 'username3', 'eyJzYWx0IjoiZTgwNjk5NTdjODQxMmFjYzhkNDIyMjE0NDgyOTdjNTgiLCJpdiI6IjhkZDI4ZDQ5ZTk2NTczMTAxYzExYjc1ODRhMGQ4NzM0IiwiYXV0aFRhZyI6IjczZDhmMWNjY2M0MGE2MzU5Nzk3ZDVjNjYyNjNkY2QyIiwiZW5jcnlwdGVkRGF0YSI6ImU2ZTI1ZjMxODA4MyJ9', 'https://gemini.google.com/', '123', 1, NULL, '{}', 1, NULL, '2025-11-30 12:04:05', '2025-12-05 19:19:49');
INSERT INTO `Passwords` VALUES ('1374f9ab-9810-48ba-a94b-65003f0fe805', '7f9e2932-a0d5-4df8-aaaa-166ad9b66600', 'fabb1853-fe14-4c1a-a6f5-a9afe6b86f1e', 'GitHub', 'username1', 'eyJzYWx0IjoiY2JmYTYxNWUxMjI5NDgwYmJlNWRmMGNjYzY0NzIyNjEiLCJpdiI6IjZlOGVjY2MzOGUzMmQ4NDhkNDViNzk2N2Y4MDUxZDQxIiwiYXV0aFRhZyI6ImMxZGY0OTIyNzZlNTY0OWFiNjg4YmZiYTdjODFiOGUxIiwiZW5jcnlwdGVkRGF0YSI6IjgwYzc0MzRhZTAwNiJ9', NULL, NULL, 1, NULL, '{}', 1, '2025-11-29 20:01:24', '2025-11-23 20:05:13', '2025-12-05 19:26:48');
INSERT INTO `Passwords` VALUES ('2db75395-bc00-4c9d-8a98-95bdb0df5139', '7f9e2932-a0d5-4df8-aaaa-166ad9b66600', 'fabb1853-fe14-4c1a-a6f5-a9afe6b86f1e', 'Clash Verge', '2581794560@qq.com', 'eyJzYWx0IjoiZDhjYTcyYTUwMTM3ZTliYjJmNDRiNDBlOGY4OTYwY2YiLCJpdiI6IjRmYWQ5ZWE5NGI4OGM0M2EwZjQwMTk3YjZjOWMzODk2IiwiYXV0aFRhZyI6IjM4MjIxMjUzNWU3ZTM0NDQwN2FkMWU4OTY0Y2FiYTk5IiwiZW5jcnlwdGVkRGF0YSI6IjliYWI0ZWM0NTA2NjNjNGYxMGU3ZjVjMjdhIn0=', 'https://www.clashverge.dev/index.html', '222', 0, NULL, '{}', 4, NULL, '2025-11-30 23:35:50', '2025-12-05 19:26:44');
INSERT INTO `Passwords` VALUES ('32ea305e-e0b9-44b7-bad4-73e8df19492e', '7f9e2932-a0d5-4df8-aaaa-166ad9b66600', 'fabb1853-fe14-4c1a-a6f5-a9afe6b86f1e', 'WeGame', 'username2', 'eyJzYWx0IjoiYmJmYmM2MTk1ZDZlM2ZhYmJmNDRmZGE2ZDhhYjk0OWUiLCJpdiI6IjY2NDZhMmZhYzEyNWRjNzNjNDM3OTBjY2RmOGQ5ZmRlIiwiYXV0aFRhZyI6IjBjNTdiZTVmYjhmMTU4OTU4NjEzNDQ1NDJjYzUzOTVhIiwiZW5jcnlwdGVkRGF0YSI6IjY4ZWVkZWU3ZTBhNCJ9', 'https://www.wegame.com.cn/home', '111', 0, '2025-12-05 16:52:34', '{}', 1, NULL, '2025-11-30 23:30:36', '2025-11-30 23:30:36');

-- ----------------------------
-- Table structure for securitylogs
-- ----------------------------
DROP TABLE IF EXISTS `securitylogs`;
CREATE TABLE `securitylogs`  (
  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `user_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `action` enum('password_accessed','password_created','password_updated','account_created','account_locked','export_data','import_data','user_role_updated','user_enabled','user_disabled') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `details` json NULL,
  `ip_address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `user_agent` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `timestamp` datetime NULL DEFAULT CURRENT_TIMESTAMP,
  `password_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `fk_security_logs_password_id`(`password_id` ASC) USING BTREE,
  CONSTRAINT `fk_security_logs_password_id` FOREIGN KEY (`password_id`) REFERENCES `passwords` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of securitylogs
-- ----------------------------
INSERT INTO `securitylogs` VALUES ('0534d7d3-78f5-4836-8b10-e77685506471', '7f9e2932-a0d5-4df8-aaaa-166ad9b66600', 'user_role_updated', '{\"ip\": \"::ffff:127.0.0.1\", \"reason\": \"管理员手动修改\", \"newRole\": \"vip\", \"userAgent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) electron-app/1.0.0 Chrome/140.0.7339.249 Electron/38.7.2 Safari/537.36\", \"targetUserId\": \"de6ce1a3-ee7e-47be-ae71-794f00564fb3\"}', '::ffff:127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) electron-app/1.0.0 Chrome/140.0.7339.249 Electron/38.7.2 Safari/537.36', '2025-12-07 19:47:56', NULL);
INSERT INTO `securitylogs` VALUES ('285e7660-0c52-4cf3-b2e7-301d11194b40', '7f9e2932-a0d5-4df8-aaaa-166ad9b66600', 'user_role_updated', '{\"ip\": \"::1\", \"reason\": \"管理员手动修改\", \"newRole\": \"user\", \"userAgent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) electron-app/1.0.0 Chrome/140.0.7339.249 Electron/38.7.2 Safari/537.36\", \"targetUserId\": \"de6ce1a3-ee7e-47be-ae71-794f00564fb3\"}', '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) electron-app/1.0.0 Chrome/140.0.7339.249 Electron/38.7.2 Safari/537.36', '2025-12-07 19:51:35', NULL);
INSERT INTO `securitylogs` VALUES ('ccc7b8c4-5ca0-4c19-ad85-d62f01ec6f10', '7f9e2932-a0d5-4df8-aaaa-166ad9b66600', 'user_disabled', '{\"targetUserId\": \"83aab7ae-9206-48c1-b6c4-51555e12f7b0\"}', NULL, NULL, '2025-12-07 17:07:10', NULL);

-- ----------------------------
-- Table structure for sequelizemeta
-- ----------------------------
DROP TABLE IF EXISTS `sequelizemeta`;
CREATE TABLE `sequelizemeta`  (
  `name` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  PRIMARY KEY (`name`) USING BTREE,
  UNIQUE INDEX `name`(`name` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb3 COLLATE = utf8mb3_unicode_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of sequelizemeta
-- ----------------------------
INSERT INTO `sequelizemeta` VALUES ('20251029100803-create-article.js');
INSERT INTO `sequelizemeta` VALUES ('20251111024915-create-user.js');
INSERT INTO `sequelizemeta` VALUES ('20251111031402-create-password.js');
INSERT INTO `sequelizemeta` VALUES ('20251111032930-create-category.js');
INSERT INTO `sequelizemeta` VALUES ('20251111033514-create-password-history.js');
INSERT INTO `sequelizemeta` VALUES ('20251111033833-create-session.js');
INSERT INTO `sequelizemeta` VALUES ('20251111034253-create-security-log.js');
INSERT INTO `sequelizemeta` VALUES ('20251112032354-add-deleted-at-to-password.js');
INSERT INTO `sequelizemeta` VALUES ('20251113110726-add-password-id-to-security-log.js');
INSERT INTO `sequelizemeta` VALUES ('20251113113100-add-password-cascade-constraints.js');
INSERT INTO `sequelizemeta` VALUES ('20251114052726-add-auth-fields-to-user.js');
INSERT INTO `sequelizemeta` VALUES ('20251114063604-remove-salt-from-user.js');
INSERT INTO `sequelizemeta` VALUES ('20251115132153-add-jti-to-session.js');
INSERT INTO `sequelizemeta` VALUES ('20251115152245-add-rtExpires-at-to-session.js');
INSERT INTO `sequelizemeta` VALUES ('20251117102818-create-log.js');
INSERT INTO `sequelizemeta` VALUES ('20251123082220-add-avatar-to-user.js');
INSERT INTO `sequelizemeta` VALUES ('20251123083507-create-like.js');
INSERT INTO `sequelizemeta` VALUES ('20251129114227-remove-expires-at-from-password.js');
INSERT INTO `sequelizemeta` VALUES ('20251203024645-remove-fields-from-user.js');
INSERT INTO `sequelizemeta` VALUES ('20251207134927-create-feedback.js');

-- ----------------------------
-- Table structure for sessions
-- ----------------------------
DROP TABLE IF EXISTS `sessions`;
CREATE TABLE `sessions`  (
  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `user_id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `jti` json NOT NULL COMMENT 'JSON object containing { at: \"at_jti\", rt: \"rt_jti\" }',
  `device_info` json NULL COMMENT '设备信息',
  `ip_address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '登录IP',
  `user_agent` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '用户代理',
  `expires_at` datetime NULL DEFAULT NULL COMMENT 'AT过期时间',
  `rt_expires_at` datetime NULL DEFAULT NULL,
  `is_active` tinyint(1) NULL DEFAULT 1 COMMENT '是否活跃',
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of sessions
-- ----------------------------
INSERT INTO `sessions` VALUES ('b19ae084-405c-4960-960f-c233851400c8', '7f9e2932-a0d5-4df8-aaaa-166ad9b66600', '\"{\\\"rt\\\":\\\"d73886da-be30-4863-8c79-9b46bc5f2b78\\\"}\"', '{\"os\": \"Windows 10\", \"type\": \"Desktop App\", \"browser\": \"Electron\", \"osVersion\": \"10\", \"browserVersion\": \"38.7.2\", \"deviceFingerprint\": \"undefined undefined\"}', '::1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) electron-app/1.0.0 Chrome/140.0.7339.249 Electron/38.7.2 Safari/537.36', '2025-12-08 00:34:38', '2025-12-15 00:04:38', 1, '2025-12-07 23:20:53', '2025-12-08 00:04:38');

-- ----------------------------
-- Table structure for Users
-- ----------------------------
DROP TABLE IF EXISTS `Users`;
CREATE TABLE `Users`  (
  `id` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '由于该字段为UUID，所以需要设置为BINARY(16)，这样可以减少存储空间并提高索引性能',
  `username` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `avatar` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `password_hash` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `token_version` int NOT NULL DEFAULT 1,
  `refresh_token_hash` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `role` enum('user','admin','vip') CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT 'user',
  `is_active` tinyint(1) NULL DEFAULT 1,
  `last_login` datetime NULL DEFAULT NULL,
  `failed_login_attempts` int NULL DEFAULT 0,
  `locked_until` datetime NULL DEFAULT NULL,
  `master_password_hint` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `username`(`username` ASC) USING BTREE,
  UNIQUE INDEX `email`(`email` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of Users
-- ----------------------------
INSERT INTO `Users` VALUES ('7f9e2932-a0d5-4df8-aaaa-166ad9b66600', 'admin123', 'admin123@example.com', 'http://xnbjb-oss.oss-cn-wuhan-lr.aliyuncs.com/uploads/2e6f26006275e86aea29b3bf3ebd10c5.jpeg', '$2b$10$ykGerTeMI7ljqdMMx5GUsuHOpBeImNSjtXmeJn21AFr0UsUFbpgdW', 6, '$2b$10$cFqqVaE7T.PT8BUbXAA55eVdoKDeDMw9tZruREtDDq0NuDyCQW3le', 'admin', 1, '2025-12-07 23:20:53', 0, NULL, NULL, '2025-11-16 01:45:45', '2025-12-08 00:04:38');
INSERT INTO `Users` VALUES ('83aab7ae-9206-48c1-b6c4-51555e12f7b0', 'yuhuo555', '1679852136@qq.com', NULL, '$2b$10$LCMtGqMIvbMNCox7FQ1puu36DON3Og1T59ClmtdlhpTHDjrG7EKtO', 1, NULL, 'user', 0, '2025-12-05 21:31:41', 0, NULL, NULL, '2025-12-06 21:31:28', '2025-12-07 17:07:10');
INSERT INTO `Users` VALUES ('c78efe25-f0f6-4e35-b0b5-171145ba4dca', 'yuhuo888', '377437076@qq.com', NULL, '$2b$10$fA97GwESSYlG83YwBEmpBuaKqmQSTSQiyGRUW4vcSZKLodfqmwUbu', 1, NULL, 'vip', 0, '2025-12-04 21:03:27', 0, NULL, NULL, '2025-12-04 16:42:02', '2025-12-06 21:27:28');
INSERT INTO `Users` VALUES ('de6ce1a3-ee7e-47be-ae71-794f00564fb3', 'yuhuo777', '1975634165@qq.com', NULL, '$2b$10$wAVbGNmHMsrtIAWKT6wmjOB.MWrrSMOfZ.EtZhWNHYxJUBg2JGH5m', 1, NULL, 'user', 1, '2025-12-03 11:43:22', 0, NULL, NULL, '2025-12-06 21:32:20', '2025-12-07 19:51:35');
INSERT INTO `Users` VALUES ('f54ec851-b493-45da-a3a5-5bd9f64d115b', 'yuhuo666', '1872848105@qq.com', 'https://xnbjb-oss.oss-cn-wuhan-lr.aliyuncs.com/uploads/41f5b1b47f9036a20c3e2c471b352fd0.jpg', '$2b$10$QbyDkCCOvoyzjm.ZWc51S.yoDwroApayoQ1kjmZyzw3WeZRjI4Tq2', 1, NULL, 'vip', 1, '2025-12-07 11:42:51', 0, NULL, NULL, '2025-11-23 22:10:40', '2025-12-07 11:43:15');

SET FOREIGN_KEY_CHECKS = 1;
